### ISSUE TITLE
(Question) using x11 output in x11-packages

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-docker#27] opened 2022-05-03 01:47 UTC
![image](https://user-images.githubusercontent.com/64093255/166393444-3d5a6b14-3137-4cc5-9397-69f25b1f5e0d.png)

hello, I am currently using Manjaro, I installed termux using docker, it works very well, but I can not start x11 packages, not even with vnc, when I run vncserver it gives me an invalid ip address, is there any way to work with these packages from docker?

**Comment by Yisus7u7** [comment] 2022-05-03 01:49
@Grimler91 any ideas?

**Comment by Grimler91** [comment] 2022-05-03 06:30
I haven't tried it but I suppose it should work, if relevant ports are accessible. See for example this thread: https://stackoverflow.com/questions/16296753/can-you-run-gui-applications-in-a-linux-docker-container

> but I can not start x11 packages

Why? What happens?

> when I run vncserver it gives me an invalid ip address

What does "invalid" mean?

**Comment by Yisus7u7** [comment] 2022-05-03 21:00
> What does "invalid" mean?

![image](https://user-images.githubusercontent.com/64093255/166565390-2d8ad507-7d87-4b47-b937-3e9c8d522655.png)

that ip address is invalid

**Comment by wmcbtech30** [comment] 2022-05-04 00:14
Closing since this is a duplicate of https://github.com/termux/termux-packages/discussions/10467 which would have been answered

**Closed by wmcbtech30** 2022-05-04 00:14 UTC
